apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-depl
spec:
  selector:
    matchLabels:
      app: minio-depl
  template:
    metadata:
      labels:
        app: minio-depl
    spec:
      containers:
        - name: minio-depl
          image: quay.io/minio/minio
          args:
            - server
            - /data
            - "--console-address=:9001"
          env:
            - name: "MINIO_ROOT_USER"
              value: "admin"
            - name: "MINIO_ROOT_PASSWORD"
              value: "admin123"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-pvc
              mountPath: /data
      volumes:
        - name: minio-pvc
          persistentVolumeClaim:
            claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  selector:
    app: minio-depl
  type: NodePort
  ports:
    - name: minio-svc
      port: 9000
      targetPort: 9000
    - name: minio-console
      port: 9001
      targetPort: 9001
