apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-depl
spec:
  selector:
    matchLabels:
      app: upload-depl
  template:
    metadata:
      labels:
        app: upload-depl
    spec:
      containers:
        - name: upload-depl
          image: mahirminhajk/s.upload
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: node-env
                  key: NODE_ENV
            - name: PORT
              value: "3000"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq-svc.my-others.svc.cluster.local:5672"
            - name: REDIS_URL
              value: "redis://upload-redis-svc.my-db.svc.cluster.local:6379"
            - name: MINIO_ENDPOINT
              value: "minio-svc"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ACCESS_KEY
              value: "km12"
            - name: MINIO_SECRET_KEY
              value: "admin123"
            - name: MINIO_BUCKET
              value: "upload"
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: upload-svc
spec:
  selector:
    app: upload-depl
  ports:
    - name: upload-svc
      protocol: TCP
      port: 3000
      targetPort: 3000
