apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  selector:
    matchLabels:
      app: admin-depl
  template:
    metadata:
      labels:
        app: admin-depl
    spec:
      containers:
      - name: admin-depl
        image: mahirminhajk/s.admin-panel
        env: 
        - name: VITE_API_URL
          value: "https://km12.dev/api/v1"
        resources:
          limits:
            memory: "768Mi"
            cpu: "1000m"
          requests:
            memory: "384Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: admin-svc
spec:
  selector:
    app: admin-depl
  ports:
  - port: 5173
    targetPort: 5173
