apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-mongo-depl
  namespace: my-db
spec:
  selector:
    matchLabels:
      app: catalog-mongo-depl
  template:
    metadata:
      labels:
        app: catalog-mongo-depl
    spec:
      containers:
      - name: catalog-mongo-depl
        image: mongo
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: catalog-mongo-storage
          mountPath: /data/db
      volumes:
      - name: catalog-mongo-storage
        persistentVolumeClaim:
          claimName: catalog-mongo-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-mongo-svc
  namespace: my-db
spec:
  selector:
    app: catalog-mongo-depl
  ports:
  - port: 27017
  type: ClusterIP

