apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pgsql-pvc
  namespace: my-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-mongo-pvc
  namespace: my-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi