apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
  namespace: my-service
spec:
  selector:
    matchLabels:
      app: user-depl
  template:
    metadata:
      labels:
        app: user-depl
    spec:
      containers:
      - name: user-depl
        image: mahirminhajk/s.user
        env: 
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          limits:
            memory: "768Mi"
            cpu: "1000m"
          requests:
            memory: "384Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: user-srv
  namespace: my-service
spec:
  selector:
    app: user-depl
  ports:
    - name: user-srv
      protocol: TCP
      port: 3000
      targetPort: 3000

