name: tests-user

on:
  pull_request:
    paths:
      - 'user-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dpendenecy
        run: cd user-service && npm install -g pnpm && pnpm i

      - name: run test
        run: cd user-service && pnpm run test
